---
- name: Install OpenTofu from official APT repository on Debian
  hosts: semaphore
  become: true
  tasks:
    - name: Add OpenTofu APT repository
      apt_repository:
        repo: 'deb [arch=amd64] https://packages.opentofu.org/ stable main'
        state: present

    - name: Add OpenTofu GPG key
      apt_key:
        url: 'https://packages.opentofu.org/opentofu/tofu/gpgkey'
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install OpenTofu
      apt:
        name: opentofu
        state: latest
