---
- name: Add OpenTofu APT repository
  apt_repository:
    ansible.builtin.repo: 'deb [arch=amd64] https://packages.opentofu.org/ stable main'
    state: present

- name: Add OpenTofu GPG key
  ansible.builtin.apt_key:
    url: 'https://packages.opentofu.org/opentofu/tofu/gpgkey'
    state: present

- name: Install OpenTofu
  ansible.builtin.apt:
    name: opentofu
    state: latest
    update_cache: true
