---
- name: Create ansible user
  ansible.builtin.user:
    name: "{{ ansible_pct_user }}"
    comment: Ansible User
    home: "{{ ansible_home }}"
    shell: "{{ ansible_shell}}"
    create_home: true
    system: true

- name: Create .ssh directory
  ansible.builtin.file:
    path: "{{ ansible_home }}/.ssh"
    state: directory
    owner: "{{ ansible_pct_user }}"
    group: "{{ ansible_group }}"
    mode: '0700'

- name: Set public key as authorized key
  ansible.builtin.copy:
    content: "{{ ansible_user_public_key }}"
    dest: "{{ ansible_home }}/.ssh/authorized_keys"
    owner: "{{ ansible_pct_user }}"
    group: "{{ ansible_group }}"
    mode: '0600'

- name: Add sudoers entry for ansible user
  ansible.builtin.copy:
    content: 'ansible ALL = (root) NOPASSWD: /usr/sbin/pct'
    dest: /etc/sudoers.d/ansible_pct
    owner: root
    group: root
    mode: '0440'
