---
semaphore_package_requirements:
  - python3-pip
  - virtualenv
semaphore_user: semaphore
semaphore_user_home: /config/semaphore
semaphore_galaxy_requirements:
  - community.general
semaphore_pip_requirements:
  - ansible
  - requests
  - paramiko

semaphore_hash: "{{ lookup('community.general.bitwarden', 'lxc-semaphore_hash', field='password')|join() }}"
semaphore_encr: "{{ lookup('community.general.bitwarden', 'lxc-semaphore_encryption', field='password')|join() }}"
semaphore_key: "{{ lookup('community.general.bitwarden', 'lxc-semaphore_key', field='password')|join() }}"
semaphore_admin: "{{ lookup('community.general.bitwarden', 'lxc-semaphore_admin', field='password')|join() }}"
semaphore_tg_bot_token: "{{ lookup('community.general.bitwarden', 'semaphore_tg_bot_token', field='password')|join() }}"
semaphore_tg_chat_id: "{{ lookup('community.general.bitwarden', 'semaphore_tg_chat_id', field='password')|join() }}"
